import React from "react";
import {Col, Layout as LayoutAnt, Row, Typography} from "antd";
import Head from "next/head";
import {motion} from "framer-motion";
import styles from 'layouts/Layout/Layout.module.scss'
import {Header} from "@/components/Header/Header";

const {Footer, Content} = LayoutAnt;
const {Text, Link: LinkAnt} = Typography
const RowM = motion(React.forwardRef(({children, ...props}, ref) => (
    <Row ref={ref} {...props}>{children}</Row>
)))

const Layout = ({children}) => {
    return (
        <LayoutAnt className={styles.Layout}>
            <div className={styles.Layout__container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                    <link rel="preconnect" href="https://fonts.googleapis.com"/>
                    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
                    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;600&display=swap"
                          rel="stylesheet"/>
                </Head>
                <Header/>
                <Content className={styles.Layout__content}>
                    {children}
                </Content>
                <Footer className={styles.Layout__footer}>
                    <RowM
                        justify={"center"}
                        align={"middle"}
                        gutter={16}
                        className={styles.Layout__footerContainer}
                        animate={{y: [-4, 4]}} transition={{repeat: Infinity, repeatType: "mirror", duration: 1.5}}
                    >
                        <Col><Text>Тыртычный Влад, группа 201-322</Text></Col>
                        <Col><LinkAnt to={'https://github.com/aposDupos/next-course-work'}
                                      target={'_blank'}>Репозиторий</LinkAnt></Col>
                    </RowM>
                </Footer>
            </div>
        </LayoutAnt>
    )
}

export default Layout